controller_list:
#-------------for real gripper-----------------------------
  - name: joint_position_controller #/simple_gripper/joint_position_controller
    action_ns: gripper_cmd #follow_joint_trajectory #Robotiq2FCommand #gripper_action #gripper_cmd
    type: GripperCommand #FollowJointTrajectory #Robotiq2FActionController #GripperCommand
    default: true
    joints:
      - finger_joint

#-------------for real UR10---------------------------------

  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
